### ISSUE TITLE
Missing Holdings in Arabia

### ISSUE THREAD

**Issue by loup99** [rickinator9/WTWSMS#51]
There is currently an issue with provinces completely withou holdings in Arabia, an issue that I do not really understand as the province files have baronies defined. Is it due to an issue with the landed_titles? Not sure, but I believe that all the titles were added by Zusk in his Arabia overhaul.

**Comment by rquinio** [comment]
There are 28 duplicated IDs in landed titles files, with some baronies being part of 2 counties.
This can explain some missing holdings.

It could be fixed by cloning them with different ids... unless they represent the same location, in which case one of the 2 should be deleted. So it might be wrong if I'm the one to do it :)

**Comment by loup99** [comment]
Cloning is the best way of doing it for now, and then we can look into changing the name.

**Comment by rquinio** [comment]
Done !

**Comment by loup99** [comment]
Will close that this too, thanks for the help with it as I was confused.
